generate:
  - types
  - client
accessModifier: public
additionalImports:
  - Foundation
  - OSLog
  - Observation
  - _Concurrency
filter:
  operations:
    - appleSignIn
    - refreshToken
    - chatChat_post
    - getConversations
    - createConversation
    - deleteConversation
    - getConversationMessages
    - createMessage
    - uploadFile
    - uploadFile_get
    - searchConversationsAndMessages
    - getBatteryStatus
    - getUserTier
    - createCheckoutSession
    - getSubscriptionStatus
    - createBillingPortalSession
    - getAvailableModels
    - listConversationsV1
    - createConversationV1
    - getConversationV1
    - updateConversationV1
    - deleteConversationV1
    - getConversationMessagesV1
    - createMessageV1
    - getUserProfileV1
    - updateUserProfileV1
    - getUsageStatisticsV1
    - uploadFileV1
    - downloadFileV1
featureFlags:
  - proposal-NNNN